### ISSUE TITLE
多环境配置文件

### ISSUE THREAD

**Issue by WalkerLu** [bailichen/vue-resume#1]
Hi，想请教下关于多文件配置文件是否可以将环境变量配置到系统环境变量中，然后不同的环境根据当前环境变量的的值去匹配配置文件呢（目前我验证不行，也可能是操作出错）。目前我看到的做法都是在构建的时候就注入了环境变量，是因为process.env读取不到系统环境变量么？

**Comment by bailichen** [comment]
构建的时候就注入了全局的环境变量，你可以根据不同的环境变量去加载不同的文件。判断条件要提前写好。

**Comment by WalkerLu** [comment]
确实是这样，在想一种只构建一次就能投放多个环境的方法。
